### ISSUE TITLE
Link in README for Geist is wrong

### ISSUE THREAD

**Issue by wallfly** [NicolasMontone/chat-with-your-base#2]
Current link to geist.sh returns an error.
It seems the site is at https://geist-ui.dev

**Comment by NicolasMontone** [comment]
Ooo you are totally right, the actual link is to -> https://vercel.com/font I will change it! Thanks ✨

**Comment by NicolasMontone** [comment]
Already fixed in commit: https://github.com/NicolasMontone/chat-with-your-base/commit/89dc5cb8a1640150b923b25bf030c02e3bff7ad0 Thanks!
